//
//  DetailsModels.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 28/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {

	enum FetchContents {
		struct Request {
		}
		struct Response {
			let detailInfo: Detailnfo
		}
		struct ViewModel {
			let name: String
			let description: String
			let iconUrl: String?
			let temperature: String
			let additionnal: [(placeholder: String, text: String)]
		}
	}
	enum FetchContentsError {
		struct Response {
			let error: Error
		}
		struct ViewModel {
			let title: String
			let message: String
			let actionTitle: String
		}
	}
}
