//
//  DetailsRouter.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 28/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic {}

protocol DetailsDataPassing {
	var dataStore: DetailsDataStore? { get }
}

class DetailsRouter: NSObject, DetailsDataPassing {

	// MARK: - Property

	weak var viewController: DetailsViewController?
	var dataStore: DetailsDataStore?
}

// MARK: - DetailsRoutingLogic

extension DetailsRouter: DetailsRoutingLogic {

}
