//
//  SplashRouter.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    func routeToHome()
}

protocol SplashDataPassing {
    var dataStore: SplashDataStore? { get }
}

class SplashRouter: NSObject, SplashDataPassing {
    weak var viewController: SplashViewController?
    var dataStore: SplashDataStore?
}

// MARK: - SplashRoutingLogic

extension SplashRouter: SplashRoutingLogic {
    func routeToHome() {
        let homeViewController = HomeModule.makeView()
        viewController?.navigationController?.setViewControllers([homeViewController], animated: false)
    }
}
