//
//  SplashViewController.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashDisplayLogic: class {
    func displayHome(viewModel: Splash.FetchContents.ViewModel)
}

class SplashViewController: UIViewController {

    // MARK: - Property

    var interactor: SplashBusinessLogic?
    var router: (NSObjectProtocol & SplashRoutingLogic & SplashDataPassing)?

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        fetchContents()
    }

    // MARK: - Private

    private func fetchContents() {
        let request = Splash.FetchContents.Request()
        interactor?.doSomething(request: request)
    }
}

// MARK: - SplashDisplayLogic

extension SplashViewController: SplashDisplayLogic {

    func displayHome(viewModel: Splash.FetchContents.ViewModel) {
        router?.routeToHome()
    }
}
