//
//  SplashInteractor.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
  func doSomething(request: Splash.FetchContents.Request)
}

protocol SplashDataStore {}

class SplashInteractor: SplashDataStore {
  var presenter: SplashPresentationLogic?
  var worker: SplashWorker?
}

// MARK: - SplashBusinessLogic

extension SplashInteractor: SplashBusinessLogic {

    func doSomething(request: Splash.FetchContents.Request) {
      worker = SplashWorker()
      worker?.doSomeWork()

      let response = Splash.FetchContents.Response()
      presenter?.presentSomething(response: response)
    }
}
