//
//  SplashInteractor.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
    func doSomething(request: Splash.FetchContents.Request)
}

protocol SplashDataStore {}

class SplashInteractor: SplashDataStore {

	// MARK: - Property

	var presenter: SplashPresentationLogic?
    let worker: SplashWorkerProtocol

	// MARK: - Initialize

	init(worker: SplashWorkerProtocol) {
		self.worker = worker
	}
}

// MARK: - SplashBusinessLogic

extension SplashInteractor: SplashBusinessLogic {

	func doSomething(request: Splash.FetchContents.Request) {
		worker.fetchContents { [weak self] in
			let response = Splash.FetchContents.Response()
			self?.presenter?.presentContents(response: response)
		}
    }
}
