//
//  SplashWorker.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashWorkerProtocol {
	func fetchContents(completionHandler: @escaping () -> Void)
}

class SplashWorker {

	// MARK: - Enum

	enum Constant {
		static let waitTime: Double = 2 // In seconds
	}
}

// MARK: - SplashWorkerProtocol

extension SplashWorker: SplashWorkerProtocol {

	func fetchContents(completionHandler: @escaping () -> Void) {
		DispatchQueue.main.asyncAfter(deadline: .now() + Constant.waitTime, execute: completionHandler)
	}
}
