//
//  HomeRouter.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToDetail()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeDataPassing {

	// MARK: - Property

	weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
}

// MARK: - HomeRoutingLogic

extension HomeRouter: HomeRoutingLogic {

	func routeToDetail() {
		let detailsViewController = DetailsModule.makeView(with: dataStore?.cityId)
		viewController?.navigationController?.pushViewController(detailsViewController, animated: true)
    }
}
