//
//  HomeModels.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {

    enum FetchContents {
        struct Request {
        }
        struct Response {
            let cityName: String
            let description: String?
            let currentTemperature: Float?
            let days: [DayInfo]
        }
        struct ViewModel {
            let name: String
            let description: String
            let currentTemperature: String
            let days: [Days]

            struct Days {
                let name: String
                let max: String
                let min: String
				let imageUrl: String?
            }
        }
    }

    enum FetchContentsError {
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let title: String
            let message: String
            let actionTitle: String
        }
    }
}
